### ISSUE TITLE
Package loading fails on Linux with Python 3.6

### ISSUE THREAD

**Issue by chmue** [kbenoit/spacyr#27]
The installation of the current master branch fails because the package cannot be loaded on Linux with Python 3.6. The specific problem is that `spacyr` thinks that the Python 3 library is `/usr/lib/libpython3.6.so` whereas it is actually `/usr/lib/libpython3.6m.so` (full output below).

The problematic line is the regular expression used to extract the version information here:
https://github.com/kbenoit/spacyr/blob/master/R/config.R.in#L24

```
downloads % wget -nv https://github.com/kbenoit/spacyr/archive/master.zip -O spacyr-master.zip
2017-04-18 16:35:43 URL:https://codeload.github.com/kbenoit/spacyr/zip/master [319603/319603] -> "spacyr-master.zip" [1]
downloads % unzip spacyr-master.zip
Archive:  spacyr-master.zip
downloads % R CMD INSTALL --build --no-inst spacyr-master/
* installing to library ‘/home/cmueller/.R/x86_64-pc-linux-gnu-library/3.3’
* installing *source* package ‘spacyr’ ...
Using python binary from PATH
configure: creating ./config.status
config.status: creating src/Makevars
config.status: creating R/config.R
** libs
g++ -I/usr/include/R/ -DNDEBUG -I/usr/include/python3.6m -I/usr/include/python3.6m -D PYTHONLIBFILE=libpython3.6.so -D_FORTIFY_SOURCE=2 -I"/home/cmueller/.R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include"   -fpic  -march=native -O2 -pipe -fstack-protector-strong  -c RcppExports.cpp -o RcppExports.o
g++ -I/usr/include/R/ -DNDEBUG -I/usr/include/python3.6m -I/usr/include/python3.6m -D PYTHONLIBFILE=libpython3.6.so -D_FORTIFY_SOURCE=2 -I"/home/cmueller/.R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include"   -fpic  -march=native -O2 -pipe -fstack-protector-strong  -c python.cpp -o python.o
g++ -shared -L/usr/lib64/R/lib -Wl,-O1,--sort-common,--as-needed,-z,relro -o spacyr.so RcppExports.o python.o -L/usr/lib -lpython3.6m -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -L/usr/lib64/R/lib -lR
installing to /home/cmueller/.R/x86_64-pc-linux-gnu-library/3.3/spacyr/libs
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error : .onLoad failed in loadNamespace() for 'spacyr', details:
  call: py_initialize(config$libpython)
  error: /usr/lib/libpython3.6.so: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/cmueller/.R/x86_64-pc-linux-gnu-library/3.3/spacyr’
downloads % ls -1 /usr/lib/libpython3.6*
/usr/lib/libpython3.6m.so
/usr/lib/libpython3.6m.so.1.0
```

**Comment by kbenoit** [comment]
Thanks @chmue, we will try to fix asap.

**Comment by amatsuo** [comment]
@chume 
It's kinda dummy way but I pushed a hotfix. Could you try installing `fix_issue27` branch? 

I won't be available for a few hours as I will be on board.

**Comment by chmue** [comment]
I don't see any code on `fix_issue27` yet. Maybe you need to `git push` your local changes?

https://github.com/kbenoit/spacyr/compare/master...fix_issue27

**Comment by amatsuo** [comment]
I pushed a new branch while ago:
https://github.com/kbenoit/spacyr/tree/fix_issue27

**Comment by chmue** [comment]
I am sorry but I can still see no commits on the new branch (I can see the branch itself though).

According to the comparison of the `fix_issue27` against the `master` branch (https://github.com/kbenoit/spacyr/compare/master...fix_issue27) there are no new commits on the `fix_issue27` branch.

**Comment by amatsuo** [comment]
Sorry. I found that I hadn't pushed a commit. Could you test when you have the time?

**Comment by chmue** [comment]
Your fix works for both Python 2 and 3 on my Linux machine. 

I think a slightly simpler solution might work as well, as you can change the regex to also allow for an "m" at the end of the version string. I pushed this to `fix-python36-error`. (Apologies for not following the naming convention.)
